# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:9.5.0

    #working_directory: ~/repo

    steps:
      - checkout
      # run tests!
      - run: npm install
      # run tests!
      - run: npm test